# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-22 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20190322_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business/'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='hood.Location'),
        ),
    ]
