# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-24 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20190323_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
        migrations.AddField(
            model_name='hood',
            name='health',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hood',
            name='police',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
