# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_hood_chief'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hood',
            old_name='name',
            new_name='neighborhood',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location',
        ),
    ]
