# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_auto_20190325_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='fire_services',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
